import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

type Screen = "home" | "login" | "register" | "forgot" | "profile" | "booking" | "contact" | "tracking";
const gold = "#D4AF37";

export default function App() {
  const [screen, setScreen] = useState<Screen>("home");
  const [signedIn, setSignedIn] = useState(false);
  const [message, setMessage] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", phone: "", password: "", confirmPassword: "", pickup: "", dropoff: "", date: "", notes: "" });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const input = (key: keyof typeof form, placeholder: string, secure = false) => <TextInput style={styles.input} value={form[key]} onChangeText={(value) => update(key, value)} placeholder={placeholder} placeholderTextColor="#7D7A73" secureTextEntry={secure} autoCapitalize={key === "email" ? "none" : "sentences"} />;
  const passwordInput = (key: "password" | "confirmPassword", placeholder: string) => <View style={styles.passwordRow}><TextInput style={styles.passwordInput} value={form[key]} onChangeText={(value) => update(key, value)} placeholder={placeholder} placeholderTextColor="#7D7A73" secureTextEntry={key === "password" ? !showPassword : !showConfirmPassword} autoCapitalize="none" /><Pressable onPress={() => key === "password" ? setShowPassword(!showPassword) : setShowConfirmPassword(!showConfirmPassword)} accessibilityLabel={(key === "password" ? showPassword : showConfirmPassword) ? "Hide password" : "Show password"} accessibilityRole="button"><EyeIcon crossed={!(key === "password" ? showPassword : showConfirmPassword)} /></Pressable></View>;
  const button = (label: string, action: () => void) => <Pressable style={styles.button} onPress={action}><Text style={styles.buttonText}>{label}</Text></Pressable>;
  const auth = (register: boolean) => <View style={styles.panel}><Text style={styles.title}>{register ? "Create your account" : "Welcome back"}</Text><Text style={styles.muted}>{register ? "Save your details for faster bookings." : "Sign in to manage your journeys."}</Text>{register && input("name", "Full name")}{input("email", "Email address")}{register && input("phone", "Phone number")}{passwordInput("password", "Password")}{register && passwordInput("confirmPassword", "Confirm password")}{register && <Text style={styles.small}>Use 8+ characters with uppercase, lowercase, a number, and a symbol.</Text>}{button(register ? "Create account" : "Log in", () => { if (register) { const requiredFields = [form.name, form.email, form.phone, form.password, form.confirmPassword]; if (requiredFields.some((value) => !value.trim())) { setMessage("Please fill in all required fields."); return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) { setMessage("Please enter a valid email address."); return; } if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/.test(form.password)) { setMessage("Use a strong password with 8+ characters, uppercase, lowercase, a number, and a symbol."); return; } if (form.password !== form.confirmPassword) { setMessage("Passwords do not match."); return; } setScreen("login"); setMessage("Account created. Please log in."); return; } setSignedIn(true); setScreen("home"); setMessage("Logged in."); })}{!register && <Pressable onPress={() => setScreen("forgot")}><Text style={styles.link}>Forgot password?</Text></Pressable>}<Pressable onPress={() => setScreen(register ? "login" : "register")}><Text style={styles.link}>{register ? "Already have an account? Log in" : "New here? Create an account"}</Text></Pressable></View>;
  const forgot = <View style={styles.panel}><Text style={styles.title}>Reset your password</Text><Text style={styles.muted}>Enter your email and we will send a reset link.</Text>{input("email", "Email address")}{button("Send reset link", () => setMessage("If that email is registered, a reset link has been sent."))}{message ? <Text style={styles.success}>{message}</Text> : null}<Pressable onPress={() => setScreen("login")}><Text style={styles.link}>Back to sign in</Text></Pressable></View>;
  const profile = <View style={styles.panel}><Text style={styles.title}>Your profile</Text><Text style={styles.muted}>Keep your booking details up to date.</Text>{input("name", "Full name")}{input("email", "Email address")}{input("phone", "Phone number")}{button("Save profile", () => setMessage("Profile saved."))}{message ? <Text style={styles.success}>{message}</Text> : null}{button("Log out", () => { setSignedIn(false); setScreen("home"); setMessage("You have been logged out."); })}</View>;
  const booking = <View style={styles.panel}><Text style={styles.title}>Book a private trip</Text><Text style={styles.muted}>Send an inquiry and our team will confirm the details.</Text>{!signedIn && <Text style={styles.notice}>Sign in before requesting a booking.</Text>}{input("pickup", "Pickup location")}{input("dropoff", "Drop-off location")}{input("date", "Travel date (YYYY-MM-DD)")}{input("notes", "Notes or special requests")}{button("Send booking inquiry", () => { if (!signedIn) setScreen("login"); else setMessage("Inquiry received. We will confirm your trip shortly."); })}{message ? <Text style={styles.success}>{message}</Text> : null}</View>;
  const contact = <View style={styles.panel}><Text style={styles.title}>Contact our team</Text><Text style={styles.muted}>Questions about a route, vehicle, or booking?</Text>{input("name", "Your name")}{input("email", "Your email")}{input("notes", "How can we help?")}{button("Send message", () => setMessage("Thanks. Our team will be in touch."))}{message ? <Text style={styles.success}>{message}</Text> : null}</View>;
  const tracking = <View style={styles.panel}><Text style={styles.title}>Ride tracking</Text><Text style={styles.muted}>Live tracking becomes available when your driver starts the trip.</Text><View style={styles.map}><Text style={styles.pin}>PIN</Text><Text style={styles.mapText}>Your driver location will appear here</Text></View><Text style={styles.status}>Booking status: confirmed</Text><Text style={styles.small}>Location sharing is limited to your active ride and stops when the trip ends.</Text></View>;
  const home = <><View style={styles.hero}><Text style={styles.kicker}>HORIZON VIP MOVE</Text><Text style={styles.heroTitle}>Travel with confidence.</Text><Text style={styles.heroCopy}>Premium private journeys between Saudi Arabia and Bahrain.</Text>{button("Book a trip", () => setScreen("booking"))}</View><Text style={styles.section}>Your journey, handled.</Text><View style={styles.row}><Feature title="Private" copy="Door-to-door service" /><Feature title="Reliable" copy="Clear booking updates" /></View><View style={styles.row}><Feature title="Supported" copy="A team you can reach" /><Feature title="Secure" copy="Protected account access" /></View></>;
  return <SafeAreaView style={styles.safe}><StatusBar style="light" /><View style={styles.header}><Pressable onPress={() => setScreen("home")}><Text style={styles.brand}>HORIZON <Text style={styles.gold}>VIP</Text></Text><Text style={styles.tagline}>PRIVATE PASSENGER TRANSPORT</Text></Pressable><Pressable onPress={() => setScreen(signedIn ? "profile" : "login")} accessibilityLabel={signedIn ? "Open profile" : "Log in"} accessibilityRole="button">{signedIn ? <ProfileIcon /> : <Text style={styles.gold}>Log in</Text>}</Pressable></View><ScrollView contentContainerStyle={styles.content}>{screen === "home" && home}{screen === "login" && auth(false)}{screen === "register" && auth(true)}{screen === "forgot" && forgot}{screen === "profile" && profile}{screen === "booking" && booking}{screen === "contact" && contact}{screen === "tracking" && tracking}</ScrollView><View style={styles.nav}><Nav label="Home" action={() => setScreen("home")} /><Nav label="Book" action={() => setScreen("booking")} /><Nav label="Contact" action={() => setScreen("contact")} />{signedIn && <Nav label="Profile" action={() => setScreen("profile")} />}</View></SafeAreaView>;
}
function Feature({ title, copy }: { title: string; copy: string }) { return <View style={styles.feature}><Text style={styles.featureTitle}>{title}</Text><Text style={styles.small}>{copy}</Text></View>; }
function Nav({ label, action }: { label: string; action: () => void }) { return <Pressable onPress={action}><Text style={styles.gold}>{label}</Text></Pressable>; }
function EyeIcon({ crossed }: { crossed: boolean }) { return <View style={iconStyles.eye}><View style={iconStyles.eyePupil} />{crossed && <View style={iconStyles.eyeSlash} />}</View>; }
function ProfileIcon() { return <View style={iconStyles.profileIcon}><View style={iconStyles.profileHead} /><View style={iconStyles.profileBody} /></View>; }
const iconStyles = StyleSheet.create({ eye: { width: 24, height: 16, borderWidth: 2, borderColor: gold, borderRadius: 12, alignItems: "center", justifyContent: "center", marginRight: 12 }, eyePupil: { width: 6, height: 6, borderRadius: 3, backgroundColor: gold }, eyeSlash: { position: "absolute", width: 26, height: 2, backgroundColor: gold, transform: [{ rotate: "-35deg" }] }, profileIcon: { width: 28, height: 28, borderWidth: 2, borderColor: gold, borderRadius: 14, alignItems: "center", justifyContent: "flex-end", paddingBottom: 3 }, profileHead: { width: 7, height: 7, borderRadius: 4, backgroundColor: gold, marginBottom: 2 }, profileBody: { width: 14, height: 7, borderTopLeftRadius: 8, borderTopRightRadius: 8, backgroundColor: gold } });
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#0D0E0D" }, header: { padding: 22, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#292822" }, brand: { color: "#F5F0E5", fontSize: 18, fontWeight: "800", letterSpacing: 1 }, gold: { color: gold, fontWeight: "700" }, tagline: { color: "#918D82", fontSize: 8, letterSpacing: 1.5, marginTop: 3 }, content: { padding: 22, paddingBottom: 100 }, hero: { paddingVertical: 48 }, kicker: { color: gold, letterSpacing: 3, fontSize: 11, fontWeight: "700", marginBottom: 18 }, heroTitle: { color: "#F8F3E9", fontSize: 42, lineHeight: 48, fontWeight: "800" }, heroCopy: { color: "#B8B3A7", fontSize: 17, lineHeight: 25, marginVertical: 20 }, button: { backgroundColor: gold, padding: 16, alignItems: "center", borderRadius: 4, marginVertical: 6 }, buttonText: { color: "#15140F", fontWeight: "800" }, section: { color: "#F8F3E9", fontSize: 24, fontWeight: "700", marginBottom: 16 }, row: { flexDirection: "row", gap: 12, marginBottom: 12 }, feature: { flex: 1, borderWidth: 1, borderColor: "#302F28", padding: 16, minHeight: 90 }, featureTitle: { color: gold, fontWeight: "800", fontSize: 16, marginBottom: 8 }, small: { color: "#918D82", fontSize: 12, lineHeight: 18 }, panel: { paddingTop: 28 }, title: { color: "#F8F3E9", fontSize: 30, lineHeight: 36, fontWeight: "800", marginBottom: 8 }, muted: { color: "#A6A196", fontSize: 15, lineHeight: 22, marginBottom: 24 }, input: { backgroundColor: "#171814", borderWidth: 1, borderColor: "#38362D", color: "#F8F3E9", borderRadius: 4, padding: 14, marginBottom: 12, fontSize: 15 }, passwordRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#171814", borderWidth: 1, borderColor: "#38362D", borderRadius: 4, marginBottom: 12 }, passwordInput: { flex: 1, color: "#F8F3E9", padding: 14, fontSize: 15 }, link: { color: gold, textAlign: "center", marginTop: 22, fontWeight: "700" }, notice: { color: "#D8B968", backgroundColor: "#252116", padding: 12, marginBottom: 16 }, success: { color: "#A9D6A1", marginTop: 16, textAlign: "center" }, map: { backgroundColor: "#202522", height: 260, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#34382F" }, pin: { color: gold, fontWeight: "800", marginBottom: 10 }, mapText: { color: "#A6A196" }, nav: { position: "absolute", bottom: 0, left: 0, right: 0, backgroundColor: "#151613", borderTopWidth: 1, borderTopColor: "#302F28", padding: 17, flexDirection: "row", justifyContent: "space-around" }, status: { color: gold, fontWeight: "700", marginTop: 18 } });